# Generated by Django 4.1.1 on 2022-10-22 08:03

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=26, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=26)),
                ("number", models.CharField(max_length=26, unique=True)),
                ("favorite", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        default=api.models.Group.default,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.group",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
