# Generated by Django 4.1.1 on 2022-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(default="No Group", max_length=26, unique=True),
        ),
    ]
