# Generated by Django 4.1.1 on 2022-10-22 07:36

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="group",
            field=models.ForeignKey(
                default=api.models.Group.default,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.group",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
